#!/usr/bin/env python3.5
"""
MULE Control software for ANDESITE

Usage:
    mule -h | --help
    mule --version
    mule

Options:
    -h --help       Show this screen and exit
    --version       Display the version and exit

"""
from docopt import docopt
import sys
from BBB_files.MULE._version import __version__

def main(inputargs):
    args = docopt(__doc__, version=__version__, argv=inputargs)

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:] if len(sys.argv) > 1 else ""))  # guaranteed to pass the right number of arguments.